proyectofinal/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::resource('productos', 'productos');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('categorias', 'categoriaspadres');
Route::resource('categoriashija', 'categoriahijas');

proyectofinal/resources/views/categoriashija/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
  <div class="col-lg-12">
    <div class="pull-left">
      <h3>Crear Categoria padre</h3>
    </div>
  </div>
</div>
@if(count($errors) > 0)
<div class="alert alert-danger">
  <strong>Whooops!! </strong> There were some problems with your input.<br>
  <ul>
    @foreach ($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif
{!! Form::open(['route' => 'categoriashija.store', 'method' => 'POST']) !!}
@include('categoriashija.form')
{!! Form::close() !!}
@endsection

proyectofinal/resources/views/categoriashija/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Editar Articulo</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('productos.index') }}">Volver</a>
        </div>
    </div>
</div>
@if (count($errors) > 0)
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
{!! Form::model($categorias, ['method' => 'PATCH','route' => ['categoriashija.update', $categorias->id]]) !!}
@include('categoriashija.form')
{!! Form::close() !!}
@endsection

proyectofinal/resources/views/categoriashija/form.blade.php
<div class="row">
  <div class="col-xs-12">
    <div class="form-group">
      <strong>nombre : </strong>
      {!! Form::text('nombre', null, ['placeholder'=>'nombre','class'=>'form-control']) !!}
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class="form-group">
        <strong>id_categoria_Padre : </strong>
        {!! Form::text('id_categoria_Padre', null, ['placeholder'=>'id_categoria_Padre','class'=>'form-control']) !!}
      </div>
    </div>
    <div class="col-xs-12">
      <a class="btn btn-xs btn-success" href="{{ route('categorias.index') }}">Back</a>
      <button type="submit" class="btn btn-xs btn-primary" name="button">Submit</button>
    </div>
  </div>

proyectofinal/resources/views/categoriashija/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
  <div class="col-lg-12">
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="pull-right">
      <a class="btn btn-xs btn-success" href="{{ route('categoriashija.create') }}">Create New categoria padre</a>
    </div>
  </div>
</div>
@if ($message = Session::get('success'))
<div class="alert alert-success">
  <p>{{ $message }}</p>
</div>
@endif
<table class="table table-bordered">
  <tr>
    <th>No.</th>
    <th>Nombre</th>
    <th>padre</th>
    <th width="300px">Actions</th>
  </tr>
  @foreach ($categorias as $categoria)
  <tr>
    <td>{{ ++$i }}</td>
    <td>{{ $categoria->nombre }}</td>
    <td>{{ $categoria->id_categoria_Padre }}</td>
    <td>
      <a class="btn btn-xs btn-primary" href="{{ route('categoriashija.edit', $categoria->id) }}">Edit</a>
      {!! Form::open(['method' => 'DELETE', 'route'=>['categoriashija.destroy', $categoria->id], 'style'=> 'display:inline']) !!}
      {!! Form::submit('Delete',['class'=> 'btn btn-xs btn-danger']) !!}
      {!! Form::close() !!}
    </td>
  </tr>
  @endforeach
</table>
{!! $categorias->links() !!}
@endsection

proyectofinal/resources/views/categoriashija/master.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Simple Crud with Resource Controller</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      @yield('content')
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>