proyectofinal/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::resource('productos', 'productos');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('categorias', 'categoriaspadres');
Route::resource('categoriashija', 'categoriahijas');

proyectofinal/app/producto.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class producto extends Model
{
    protected $fillable = [
        'SKU', 'nombre', 'descripcion', 'imagen', 'categorias', 'Stock', 'precio',
    ];
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

proyectofinal/app/Http/Controllers/productos.php
<?php
namespace App\Http\Controllers;

use App\producto;
use Illuminate\Http\Request;

class productos extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
///llama  a la vista index
    public function index()
    {
        $productos = producto::paginate(5);
        return view('Producto.index', compact('productos'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }
///llama a crear categoria
    public function create()
    {
        $tiendas = "";
        return view('Producto.create', compact('tiendas'));
    }
//almacena los datos
    public function store(Request $request)
    {
        $this->validate($request, [
            'nombre'      => 'required',
            'SKU'         => 'required',
            'descripcion' => 'required',
            'imagen'      => 'required',
            'Stock'       => 'required',
            'precio'      => 'required',
        ]);
        producto::create($request->all());
        return redirect()->route('productos.index')
            ->with('success', 'Producto creado correctamente');
    }
///muestra los datos
    public function show($id)
    {
        $producto = producto::find($id);
        return view('Producto.show', compact('producto'));
    }
///llama a la vista editar
    public function edit($id)
    {
        $productos = producto::find($id);
        return view('Producto.edit', compact('productos'));
    }
///proceso para actualizar
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nombre'      => 'required',
            'SKU'         => 'required',
            'descripcion' => 'required',
            'imagen'      => 'required',
            'Stock'       => 'required',
            'precio'      => 'required',
        ]);
        producto::find($id)->update($request->all());
        return redirect()->route('productos.index')
            ->with('success', 'producto actualizada correctamente');
    }
///proceso  para destruidos
    public function destroy($id)
    {
        producto::find($id)->delete();
        return redirect()->route('productos.index')
            ->with('success', 'producto eliminada correctamente');
    }
}

proyectofinal/resources/views/Producto/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Crear Articulo</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('productos.index') }}"> Volver</a>
        </div>
    </div>
</div>
{!! Form::model($tiendas,array('route' => 'productos.store','method'=>'POST')) !!}
@include('Producto.form')
{!! Form::close() !!}
@endsection

proyectofinal/resources/views/Producto/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Editar Articulo</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('productos.index') }}">Volver</a>
        </div>
    </div>
</div>
@if (count($errors) > 0)
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
{!! Form::model($productos, ['method' => 'PATCH','route' => ['productos.update', $productos->id]]) !!}
@include('Producto.form')
{!! Form::close() !!}
@endsection

proyectofinal/resources/views/Producto/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>SKU:</strong>
            {!! Form::text('SKU', null, array('placeholder' => 'SKU','class' => 'form-control')) !!}
            @if ($errors->has('SKU'))
            <span class="help-block">
                <strong>{{ $errors->first('SKU') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>nombre:</strong>
            {!! Form::text('nombre', null, array('placeholder' => 'nombre','class' => 'form-control')) !!}
            @if ($errors->has('nombre'))
            <span class="help-block">
                <strong>{{ $errors->first('nombre') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>descripcion:</strong>
            {!! Form::text('descripcion', null, array('placeholder' => 'descripcion','class' => 'form-control')) !!}
            @if ($errors->has('descripcion'))
            <span class="help-block">
                <strong>{{ $errors->first('descripcion') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>imagen:</strong>
            {!! Form::text('imagen', null, array('placeholder' => 'imagen','class' => 'form-control')) !!}
            @if ($errors->has('imagen'))
            <span class="help-block">
                <strong>{{ $errors->first('imagen') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>categorias:</strong>
            {!! Form::text('categorias', null, array('placeholder' => 'categorias','class' => 'form-control')) !!}
            @if ($errors->has('categorias'))
            <span class="help-block">
                <strong>{{ $errors->first('categorias') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Stock:</strong>
            {!! Form::text('Stock', null, array('placeholder' => 'Stock','class' => 'form-control')) !!}
            @if ($errors->has('Stock'))
            <span class="help-block">
                <strong>{{ $errors->first('Stock') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>precio:</strong>
            {!! Form::text('precio', null, array('placeholder' => 'precio','class' => 'form-control')) !!}
            @if ($errors->has('precio'))
            <span class="help-block">
                <strong>{{ $errors->first('precio') }}</strong>
            </span>
            @endif
        </div>
    </div>
    {!! Form::hidden('user_id', Auth::id() )!!}
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Guardar</button>
    </div>
</div>

proyectofinal/resources/views/Producto/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Articulos</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('productos.create') }}">Crear un Articulo</a>
        </div>
    </div>
</div>
@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif
<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>SKU</th>
        <th>nombre</th>
        <th>descripcion</th>
        <th>categorias</th>
        <th>Stock</th>
        <th>precio</th>
        <th>imagen</th>
        <th width="280px">Action</th>
    </tr>
    @foreach ($productos as $producto)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $producto->SKU}}</td>
        <td>{{ $producto->nombre}}</td>
        <td>{{ $producto->descripcion}}</td>
        <td>{{ $producto->categorias}}</td>
        <td>{{ $producto->Stock}}</td>
        <td>{{ $producto->precio}}</td>
        <?php
//aquí coges de donde sea la ruta que quieres mostrar
$ruta = $producto->imagen;
?>
        <td><img src="<?php echo $ruta; ?>" width='238' height='100'>
        </td>
        <td>
            <a class="btn btn-info" href="{{ route('productos.show',$producto->id) }}">Consultar</a>
            <a class="btn btn-primary" href="{{ route('productos.edit',$producto->id) }}">Editar</a>
            {!! Form::open(['method' => 'DELETE','route' => ['productos.destroy', $producto->id],'style'=>'display:inline']) !!}
            {!! Form::submit('Eliminar', ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
        </td>
    </tr>
    @endforeach
</table>
{!! $productos->links() !!}
@endsection

proyectofinal/resources/views/Producto/master.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Simple Crud with Resource Controller</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      @yield('content')
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>

proyectofinal/resources/views/Producto/show.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Articulo</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('productos.index') }}">Volver</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>SKU :</strong>
            {{ $producto->SKU}}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Articulo:</strong>
            @php
            echo $producto['nombre'] . ' ('. $producto['precio'] .')';
            @endphp
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>descripcion :</strong>
            {{ $producto->descripcion}}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>categoria:</strong>
            {{ $producto->categorias}}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>imagen:</strong>
            {{ $producto->imagen}}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Stock:</strong>
            {{ $producto->Stock}}
        </div>
    </div>
</div>
@endsection